openapi: 3.1.0

info:
  title: API сервер для проекта «Шесть городов»
  description: Список ресурсов и маршрутов сервера «Шесть городов».
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: users
    description: Действия с пользователем.
  - name: comments
    description: Действия с комментариями.
  - name: offers
    description: Действия с объявлениями.

paths:
  /user/register:
    $ref: "./user.paths.yml#/register"
  /user/login:
    $ref: "./user.paths.yml#/login"
  /user/logout:
    $ref: "./user.paths.yml#/logout"

  /comments/{offerId}:
    $ref: "./comment.paths.yml#/comments"
